### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by atanu2679** [3ct0s/disctopia-c2#100]
![Capture](https://user-images.githubusercontent.com/75174754/232093528-b315dbc0-52a6-477d-b525-e983f08ce296.PNG)

i even change this with crypto
then again change this with cryptodome, still its showing error

**Comment by 3ct0s** [comment]
Your python installation in wine should have pywin32 version (303) installed and it should work. Did you run the installation script? It takes care of all the dependencies.

**Comment by atanu2679** [comment]
You can close this after w days of working its now running successfully.

And can you change the Crypto.Cipher bcoz its throwing error.. I'm useing
Cryptodome.Cipher
