### ISSUE TITLE
Wrong wine path?

### ISSUE THREAD

**Issue by hidde-s** [3ct0s/disctopia-c2#103]
I was getting this error when running setup.sh  : wine: failed to open "/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/python.exe": c0000135

I fixed this by modifying the path in setup.sh line 49 and 47 to "/root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/python.exe"
I don't know if this was just for me or if anyone else had this issue?

**Comment by 3ct0s** [comment]
What OS did you use to run disctopia? Was it Kali?

**Comment by hidde-s** [comment]
Yes, I was using Kali.

**Comment by atanu2679** [comment]
> I was getting this error when running setup.sh : wine: failed to open "/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/python.exe": c0000135
> 
> I fixed this by modifying the path in setup.sh line 49 and 47 to "/root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/python.exe" I don't know if this was just for me or if anyone else had this issue?

i think you did something wrong, mine is work perfectly

**Comment by Deltatoolbox** [comment]
I think i have the same issue i wll try it when im at home

**Comment by Ayushbohra** [comment]
./setup.sh: line 54: /root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/python.exe: No such file or directory
wine: failed to open "/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/python.exe": c0000135
Getting the same issue

**Comment by Ayushbohra** [comment]
I'm using Kali Linux.
