### ISSUE TITLE
Screenshot dont work

### ISSUE THREAD

**Issue by Deltatoolbox** [3ct0s/disctopia-c2#104]
![image](https://user-images.githubusercontent.com/131028767/235355493-34f479a5-ce3c-493f-9173-3e36c62726ba.png)

**Comment by 3ct0s** [comment]
Something must have gone wrong with the setup or installation and some packages are missing. Can you please run the setup again and try to build a backdoor again?

**Comment by atanu2679** [comment]
> ![image](https://user-images.githubusercontent.com/131028767/235355493-34f479a5-ce3c-493f-9173-3e36c62726ba.png)

build it properly

**Comment by 3ct0s** [comment]
Did you build from a Kali machine? Are you certain there were no errors during the setup?

**Comment by atanu2679** [comment]
> ![image](https://user-images.githubusercontent.com/131028767/235355493-34f479a5-ce3c-493f-9173-3e36c62726ba.png)

text me i will build it for i already help 2 people through discord
my discord id SNOW#7171

**Comment by Deltatoolbox** [comment]
> 

i added you

**Comment by Deltatoolbox** [comment]
i got an error by setup fixed it with the path in line 47 and 49 replaced by:
"/root/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/python.exe" @3ct0s
