### ISSUE TITLE
Know how to fix this?

### ISSUE THREAD

**Issue by MonarchServer** [3ct0s/disctopia-c2#105]
Can someone give me the command to installed on window I would really love to use the old disctopia

Traceback (most recent call last):
  File "C:\Users\tybas\Downloads\disctopia-c2-main (1)\disctopia-c2-main\builder.py", line 256, in <module>
    subprocess.call(compile_command)
  File "C:\Users\tybas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\tybas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 971, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\tybas\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1440, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by Deltatoolbox** [comment]
I think you cant use that one on Windos but i can give you The old one if you want
add me on discord TornLotus#5719

**Comment by 3ct0s** [comment]
Windows is no longer an option. I don't recommend using the old version as it has bugs and you are missing out on new features. You should be using Kali and you can literally do it in 5 minutes by following my video: https://www.youtube.com/watch?v=O3pGJcVRM9k

**Comment by Deltatoolbox** [comment]
yeah you are right it is the better option, or if you dont want to i can build it for you

**Comment by MonarchServer** [comment]
> I think you cant use that one on Windos but i can give you The old one if you want add me on discord TornLotus#5719

I add you on discord already.

**Comment by MonarchServer** [comment]
> Windows is no longer an option. I don't recommend using the old version as it has bugs and you are missing out on new features. You should be using Kali and you can literally do it in 5 minutes by following my video: https://www.youtube.com/watch?v=O3pGJcVRM9k

sadly, my computer are not capable of using Kali Linux i try many time but it too laggy due to my PC being potato

**Comment by atanu2679** [comment]
> > Windows is no longer an option. I don't recommend using the old version as it has bugs and you are missing out on new features. You should be using Kali and you can literally do it in 5 minutes by following my video: https://www.youtube.com/watch?v=O3pGJcVRM9k
> 
> sadly, my computer are not capable of using Kali Linux i try many time but it too laggy due to my PC being potato

lmao
