### ISSUE TITLE
Builder issue

### ISSUE THREAD

**Issue by hg30393039** [3ct0s/disctopia-c2#109]
Hi!
When I tried to build the backdoor I received an error saying the path to pyinstaller was not right so I changed it in builder.py to the actual path:
~/.wine/drive_c/users/root/AppData/Local/Programs/Python/Python38-32/Scripts/pyinstaller

However, now i receive the following error message when building:

─# 192 INFO: PyInstaller: 3.5+498e6ee058
192 INFO: Python: 3.11.2
196 INFO: Platform: Linux-6.1.0-kali9-amd64-x86_64-with-glibc2.36
196 INFO: wrote /opt/disctopia-c2/SpotifyUpdater.spec
199 INFO: UPX is available.
Traceback (most recent call last):
  File "/root/.wine/dosdevices/c:/users/root/AppData/Local/Programs/Python/Python38-32/Scripts/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/opt/disctopia-c2/SpotifyUpdater.spec", line 6, in <module>
    a = Analysis(['SpotifyUpdater.py'],
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 190, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script '/opt/disctopia-c2/SpotifyUpdater.py' not found

No Exe-file is being created only an empty /dist folder and a .spec file.

What to do?

**Comment by hg30393039** [comment]
After adding some debug statements it shows that the .py file was created but apparently got removed in the process: 

[+] Building backdoor...
Value of list[0]: JavaUpd
File JavaUpd.py created successfully

[+] The Backdoor can be found inside the "dist" directory

**Comment by 3ct0s** [comment]
I am not sure what SpotifyUpdater.py is about. Don't remember adding that there

**Comment by hg30393039** [comment]
I put "SpotifyUpdater" as value when I set the name in the builder.

**Comment by hg30393039** [comment]
Now that i seem to have fixed the paths to python in setup.sh and the path to pyinstaller in builder.py, i get this error when building: 

[+] discord > build
[?] Are you sure you want to build the backdoor? (y/n)
y
[+] Building backdoor...
247 INFO: PyInstaller: 5.3
247 INFO: Python: 3.8.10
312 INFO: Platform: Windows-10-10.0.18362
314 INFO: wrote Z:\opt\disctopia-c2\Disc.spec
321 INFO: UPX is not available.
328 INFO: Extending PYTHONPATH with paths
['Z:\\opt\\disctopia-c2']
wine: Unhandled illegal instruction at address 05B369C9 (thread 012c), starting debugger...
Unhandled exception: illegal instruction in 32-bit code (0x05b369c9).
Register dump:
 CS:0023 SS:002b DS:002b ES:002b FS:006b GS:0063
 EIP:05b369c9 ESP:0070e108 EBP:0070e114 EFLAGS:00010212(  R- --  I   -A- - )
 EAX:3a800000 EBX:00000001 ECX:00007c00 EDX:00001400
 ESI:02e5e030 EDI:0601a2e8
Stack dump:
0x0070e108:  05af9690 00001fa0 0601a2e8 0070e13c
0x0070e118:  05ba68dd 3a800000 00000000 05ebbb60
0x0070e128:  00000000 3a800000 00000000 00000002
0x0070e138:  0070e148 0070e304 05c8b5d9 0070e238
0x0070e148:  0070e1a0 0070e1b8 00000000 0070e444
0x0070e158:  05c8d5fa 0070e304 0070e238 0070e1a0
Backtrace:
=>0 0x05b369c9 in _multiarray_umath.cp38-win32.py (+0x269c9) (0x0070e114)
  1 0x05ba68dd in _multiarray_umath.cp38-win32.py (+0x968dd) (0x0070e13c)
  2 0x05c8b5d9 in _multiarray_umath.cp38-win32.py (+0x17b5d9) (0x0070e304)
  3 0x05d81d10 (0x05d82148)
0x05b369c9 _multiarray_umath.cp38-win32.py+0x269c9: ldsl        %edx,%edi
Modules:
Module  Address                 Debug info      Name (122 modules)
PE      001b0000-001c4000       Deferred        vcruntime140
PE      00400000-0041a000       Deferred        python
PE      01420000-016f0000       Deferred        crypt32
PE      01930000-0193f000       Deferred        python3
PE      01940000-01955000       Deferred        _bz2.pyd
PE      01960000-01987000       Deferred        _lzma.pyd
PE      019d0000-019fa000       Deferred        pyexpat.pyd
PE      01a40000-01a52000       Deferred        _socket.pyd
PE      01a60000-01a68000       Deferred        select.pyd
PE      01af0000-01b0e000       Deferred        win32api.pyd
PE      01b10000-01b31000       Deferred        pywintypes38
PE      01b40000-01fcc000       Deferred        ole32
PE      01fd0000-021ef000       Deferred        rpcrt4
PE      021f0000-0222c000       Deferred        msv1_0
PE      02230000-02238000       Deferred        _win32sysloader.pyd
PE      02240000-022b3000       Deferred        pythoncom38
PE      022c0000-02346000       Deferred        winex11
PE      02c40000-02c6b000       Deferred        _cffi_backend.cp38-win32.pyd
PE      02f70000-02f8e000       Deferred        _ctypes.pyd
PE      02f90000-02f98000       Deferred        libffi-7
PE      02fe0000-046d3000       Deferred        libopenblas_v0.3.21-gcc_8_3_0
PE      05b10000-05d7a000       Export          _multiarray_umath.cp38-win32.pyd
PE      05e80000-05e92000       Deferred        _multiarray_tests.cp38-win32.pyd
PE      05f20000-05f39000       Deferred        _umath_linalg.cp38-win32.pyd
PE      05f80000-05f96000       Deferred        _pocketfft_internal.cp38-win32.pyd
PE      067e0000-06866000       Deferred        mtrand.cp38-win32.pyd
PE      06870000-06892000       Deferred        bit_generator.cp38-win32.pyd
PE      068a0000-068cc000       Deferred        _common.cp38-win32.pyd
PE      068d0000-068db000       Deferred        _hashlib.pyd
PE      068e0000-06b09000       Deferred        libcrypto-1_1
PE      06b10000-06b4a000       Deferred        _bounded_integers.cp38-win32.pyd
PE      06b90000-06ba2000       Deferred        _mt19937.cp38-win32.pyd
PE      06bb0000-06bc1000       Deferred        _philox.cp38-win32.pyd
PE      06bd0000-06be4000       Deferred        _pcg64.cp38-win32.pyd
PE      06bf0000-06bfd000       Deferred        _sfc64.cp38-win32.pyd
PE      06c00000-06c9a000       Deferred        _generator.cp38-win32.pyd
PE      10000000-103fa000       Deferred        python38
PE      622c0000-62356000       Deferred        rsaenh
PE      62500000-628ff000       Deferred        oleaut32
PE      63080000-630aa000       Deferred        zlib1
PE      643c0000-6444c000       Deferred        ws2_32
PE      646c0000-64746000       Deferred        iphlpapi
PE      64a80000-64ad8000       Deferred        win32u
PE      65680000-65900000       Deferred        msvcrt
PE      66080000-66180000       Deferred        shlwapi
PE      66640000-6665c000       Deferred        version
PE      667c0000-66809000       Deferred        shcore
PE      67500000-67552000       Deferred        imm32
PE      684c0000-68610000       Deferred        combase
PE      68880000-68d46000       Deferred        user32
PE      68e40000-68ec3000       Deferred        netapi32
PE      69840000-69938000       Deferred        advapi32
PE      6a600000-6a626000       Deferred        kerberos
PE      6aac0000-6ada1000       Deferred        ucrtbase
PE      6bbc0000-6bc59000       Deferred        sechost
PE      6c100000-6c2a5000       Deferred        wininet
PE      6d480000-6d515000       Deferred        secur32
PE      6da80000-6dc9c000       Deferred        gdi32
PE      6e200000-6e245000       Deferred        bcrypt
PE      6ecc0000-6ed00000       Deferred        dnsapi
PE      6f6c0000-6f6dd000       Deferred        nsi
PE      70380000-7060f000       Deferred        urlmon
PE      70d80000-70e23000       Deferred        uxtheme
PE      712c0000-71318000       Deferred        mpr
PE      71400000-720aa000       Deferred        shell32
PE      7b000000-7b51b000       Deferred        kernelbase
PE      7b600000-7b756000       Deferred        kernel32
PE      7bc00000-7beba000       Deferred        ntdll
ELF     7d000000-7d005000       Deferred        <wine-loader>
ELF     7eb23000-7eb2b000       Deferred        libxfixes.so.3
ELF     7eb2b000-7eb38000       Deferred        libxcursor.so.1
ELF     7eb38000-7eb4d000       Deferred        libxi.so.6
ELF     7eb4d000-7eb52000       Deferred        libxcomposite.so.1
ELF     7eb52000-7eb61000       Deferred        libxrandr.so.2
ELF     7eb61000-7eb6f000       Deferred        libxrender.so.1
ELF     7eb6f000-7eb76000       Deferred        libxxf86vm.so.1
ELF     7eb76000-7eb85000       Deferred        libmd.so.0
ELF     7eb85000-7eb9c000       Deferred        libbsd.so.0
ELF     7eb9c000-7ebca000       Deferred        libxcb.so.1
ELF     7ebca000-7ed1b000       Deferred        libx11.so.6
ELF     7ed1b000-7ed31000       Deferred        libxext.so.6
ELF     7ed4d000-7edd8000       Deferred        winex11.so
ELF     7edd8000-7ee32000       Deferred        libgssapi_krb5.so.2
ELF     7ee32000-7ee44000       Deferred        libresolv.so.2
ELF     7ee44000-7ee4b000       Deferred        libkeyutils.so.1
ELF     7ee4b000-7ee5b000       Deferred        libkrb5support.so.0
ELF     7ee5b000-7ee8b000       Deferred        libk5crypto.so.3
ELF     7ee8b000-7ef69000       Deferred        libkrb5.so.3
ELF     7ef6a000-7ef6f000       Deferred        libxinerama.so.1
ELF     7ef6f000-7ef76000       Deferred        libxdmcp.so.6
ELF     7ef76000-7ef7b000       Deferred        libxau.so.6
ELF     7ef7b000-7ef80000       Deferred        msv1_0.so
ELF     7ef80000-7ef85000       Deferred        netapi32.so
ELF     7ef85000-7f013000       Deferred        libgmp.so.10
ELF     7f013000-7f05d000       Deferred        libhogweed.so.6
ELF     7f05d000-7f0ac000       Deferred        libnettle.so.8
ELF     7f0ac000-7f0c2000       Deferred        libtasn1.so.6
ELF     7f0c2000-7f277000       Deferred        libunistring.so.2
ELF     7f277000-7f2aa000       Deferred        libidn2.so.0
ELF     7f2aa000-7f400000       Deferred        libp11-kit.so.0
ELF     7f400000-7f647000       Deferred        libgnutls.so.30
ELF     7f648000-7f650000       Deferred        kerberos.so
ELF     7f650000-7f65a000       Deferred        libffi.so.8
ELF     7f65c000-7f661000       Deferred        libcom_err.so.2
ELF     7f661000-7f66b000       Deferred        secur32.so
ELF     7f66b000-7f670000       Deferred        dnsapi.so
ELF     7f670000-7f676000       Deferred        crypt32.so
ELF     7f676000-7f682000       Deferred        bcrypt.so
ELF     7f682000-7f688000       Deferred        ws2_32.so
ELF     7f6f5000-7f721000       Deferred        libexpat.so.1
ELF     7f721000-7f774000       Deferred        libfontconfig.so.1
ELF     7f774000-7f7b1000       Deferred        libpng16.so.16
ELF     7f7b1000-7f881000       Deferred        libfreetype.so.6
ELF     7f881000-7f986000       Deferred        libm.so.6
ELF     7fe02000-7fe25000       Deferred        libbrotlicommon.so.1
ELF     7fe25000-7fe33000       Deferred        libbrotlidec.so.1
ELF     7fe33000-7fe50000       Deferred        libz.so.1
ELF     7fe6c000-7ffe0000       Deferred        win32u.so
ELF     f7c00000-f7e28000       Deferred        libc.so.6
ELF     f7ec5000-f7eca000       Dwarf           libwine.so.1
ELF     f7eca000-f7f78000       Deferred        ntdll.so
ELF     f7f80000-f7fb5000       Deferred        ld-linux.so.2
Threads:
process  tid      prio    name (all IDs are in hex)
00000020 pyinstaller.exe
        00000024    0
00000038 services.exe
        0000003c    0
        00000040    0     wine_rpcrt4_server
        0000004c    0     wine_rpcrt4_io
        00000078    0     wine_rpcrt4_io
        00000084    0     wine_rpcrt4_io
        000000b4    0     wine_rpcrt4_io
        000000cc    0     wine_rpcrt4_io
        000000e4    0     wine_rpcrt4_io
00000044 winedevice.exe
        00000048    0
        00000054    0
        00000060    0     wine_sechost_service
        00000064    0
        00000068    0
        0000006c    0
        000000d8    0
00000058 explorer.exe
        0000005c    0
        00000098    0
        000000a0    0     wine_rpcrt4_server
00000070 winedevice.exe
        00000074    0
        0000007c    0
        00000080    0     wine_sechost_service
        00000088    0
        0000008c    0
        00000090    0
        00000094    0
        0000009c    0
000000ac plugplay.exe
        000000b0    0
        000000b8    0
        000000bc    0     wine_sechost_service
        000000c0    0     wine_rpcrt4_server
000000c4 svchost.exe
        000000c8    0
        000000d0    0
        000000d4    0     wine_sechost_service
000000dc rpcss.exe
        000000e0    0
        000000e8    0
        000000ec    0     wine_sechost_service
        000000f0    0     wine_rpcrt4_server
        000000f4    0     wine_rpcrt4_server
        000000f8    0     wine_rpcrt4_io
00000100 conhost.exe
        00000104    0
00000108 python.exe
        0000010c    0
00000128 (D) C:\users\root\AppData\Local\Programs\Python\python38-32\python.exe
        0000012c    0 <==
        00000140    0
        0000014c    0
System information:
    Wine build: wine-8.0 (Debian 8.0~repack-4)
    Platform: i386 (WOW64)
    Version: Windows 7
    Host system: Linux
    Host version: 6.1.0-kali9-amd64

**Comment by Huagen1** [comment]
please where to find the backdoor after building
