### ISSUE TITLE
Commands 

### ISSUE THREAD

**Issue by rogldicksn** [3ct0s/disctopia-c2#12]
Hi,

!credentials cmd doesn't work well. it gets empty data when executed. 

Key Logger display

![image](https://user-images.githubusercontent.com/76434629/152023325-570fe643-71ca-4e94-a285-5bc86dcf093e.png)

can keylogger report be modified

**Comment by 3ct0s** [comment]
Hi There,
This could mean that there are no saved credentials from the Chrome browser. Have you ever saved any credentials on chrome?
Also, the keylogger form does not change, it will only change if the message is over 2000 characters, it will send a file with the logged keystrokes instead.
