### ISSUE TITLE
help?

### ISSUE THREAD

**Issue by Epik123** [3ct0s/disctopia-c2#13]
![image](https://user-images.githubusercontent.com/85456368/152474954-a6741057-509f-410d-b3fd-63966eaabef0.png)

**Comment by Epik123** [comment]
that was made by pyinstaller

**Comment by Epik123** [comment]
i get this error when using your builder 
![image](https://user-images.githubusercontent.com/85456368/152475410-0f047547-44e0-4331-86f3-f3d3ce47f924.png)

**Comment by 3ct0s** [comment]
Hi There,
Can you please tell me the platform you are using disctopia on? Is it Windows or Linux?
We recommend using Linux over Windows since it has fewer problems.

**Comment by Epik123** [comment]
i tried both kali and windows windows gets those errors and the setup.sh killed my linux vm

**Comment by 3ct0s** [comment]
You can always try to import a new Kali Linux VM and try again. So get a new Kali Linux VM and run the installer as mentioned in the instructions. I suggest doing that and letting us know how it goes.

**Comment by Linux-Error** [comment]
I've tried a couple of times, but each time I run setup-new.sh it kills my Kali VM. When I try to boot into it again it enters a minimal installation mode and I'm not sure what the issue is. If you know of a fix please let me know!

**Comment by 3ct0s** [comment]
What Kali Version are you using? Did your Kali machine sleep while running the setup-new.sh file?
