### ISSUE TITLE
i cant build application 

### ISSUE THREAD

**Issue by tarekxxx** [3ct0s/disctopia-c2#18]
i install wine but cannot found this 

Run "help" to get the help menu
[+] > build

Are you sure everything is setup correctly? Y/N 
y

[+] Building the Backdoor
[+] Please wait...

wine: cannot find '/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe'

[+] The Backdoor can be found inside the "dist" directory

any hint for help me

iam using kali linux !

**Comment by 3ct0s** [comment]
Hi There,
Did you run the setup.sh file? It looks like Python was not installed on wine.

**Comment by Clixzas** [comment]
Im having the same issue on parrot linux when I ran setup.sh and got this error like 30 times:
0038:err:mscoree:LoadLibraryShim error reading registry key for installroot
Then when I went to build it it gave me this error:
wine: cannot find '/home/user/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe'

**Comment by 3ct0s** [comment]
Hi There,
@Clixzas did you run it with sudo or root privileges? Let me know.

**Comment by Clixzas** [comment]
Yep I ran with root privileges or sudo

**Comment by tarekxxx** [comment]
its working when i install python
python-3.8.9.exe
