### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by TheskiddoMega** [3ct0s/disctopia-c2#21]
Im on windows and when I Tried to build it said

Traceback (most recent call last):
line 186, in <module>
    builder.build()
 line 44, in build
    self.compile()
 line 53, in compile
    subprocess.call(compile_command)
  
FileNotFoundError: [WinError 2] The system cannot find the file specified

**Comment by 3ct0s** [comment]
Hi There,
Are you using onedrive? Can you please show me the path to disctopia-c2 from the Command Line?
Was the setup successful without errors?
