### ISSUE TITLE
Can't clone the repository

### ISSUE THREAD

**Issue by unnnnnnnnnn** [3ct0s/disctopia-c2#25]
I'm trying to clone the repository using this command "git clone https://github.com/3ct0s/disctopia-c2.git" in my cmd but an error appeared "'git' is not recognized as an internal or external command, operable program or batch file.". What should i do now?

**Comment by atwoyearold14** [comment]
ummmmm, are you on windows?
you need to install git bash

**Comment by unnnnnnnnnn** [comment]
> ummmmm, are you on windows? you need to install git bash
