### ISSUE TITLE
getting error when running install file

### ISSUE THREAD

**Issue by Grimet14** [3ct0s/disctopia-c2#26]
getting this error

![image](https://user-images.githubusercontent.com/97934952/155922459-46053e4b-99a7-4f10-a0da-02de93a66c71.png)

**Comment by unnnnnnnnnn** [comment]
same here
![image](https://user-images.githubusercontent.com/93212132/155924759-acf176a6-8d89-4664-864b-97271bcf10aa.png)

**Comment by 3ct0s** [comment]
People get this issue when they try to run the installer for the second time. Please do the following:
1. Manually run the python-3.8.9.exe file and click on Uninstall (If it gives you an error move to the next step)
2. Again manually run the python-3.8.9.exe file and Click on Repair.
3. After the repair is done you should be able to run the PowerShell command again with no issues.

**Comment by unnnnnnnnnn** [comment]
> It is part of the fix please do as I said and let me know how it goes .

uhhh i can't find my python - 3.8.9 file, can i add u on discord or something?

**Comment by unnnnnnnnnn** [comment]
> People get this issue when they try to run the installer for the second time. Please do the following:
> 
> 1. Manually run the python-3.8.9.exe file and click on Uninstall (If it gives you an error move to the next step)
> 2. Again manually run the python-3.8.9.exe file and Click on Repair.
> 3. After the repair is done you should be able to run the PowerShell command again with no issues.

so ia have python 3.10.2 on my computer, not the 3.8.9 one, so did i need to do the exact same thing with my 3.10.2 exe?

**Comment by unnnnnnnnnn** [comment]
wait nvm i found that python 3.8.9 now

**Comment by unnnnnnnnnn** [comment]
but i still don't know wdym, like run the python-3.8.9.exe file, then click on uninstall?? so do i need to close the cmd, then right-click on the exe file and click on the unistall or what?
