### ISSUE TITLE
Stuck

### ISSUE THREAD

**Issue by elliotlounds** [3ct0s/disctopia-c2#30]
Hi, whenever running the build command after running the "sudo python3 builder.py" i keep getting the error "wine: cannot find '/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe'"

Pls help thank you

**Comment by elliotlounds** [comment]
![image](https://user-images.githubusercontent.com/101060850/156934939-b522a2b5-fde6-48bb-8518-8499846f0e47.png)

**Comment by yasinworks** [comment]
have you done this?
cd disctopia-c2
sed $'s/\r$//' ./setup.sh > ./setup-new.sh 
chmod +x setup-new.sh
sudo ./setup-new.sh

**Comment by 3ct0s** [comment]
Thanks for the help @yasinworks, yes it appears that pyinstaller was not installed which means that the installer failed or you forgot to run it.

**Comment by elliotlounds** [comment]
![image](https://user-images.githubusercontent.com/101060850/156941229-a826c95b-bee0-4877-b69f-0e3e5c1f84e2.png)

**Comment by elliotlounds** [comment]
I got this error

**Comment by 3ct0s** [comment]
I replied to your other issue.
