### ISSUE TITLE
Now my backdoor is not getting executed.

### ISSUE THREAD

**Issue by harryk26005** [3ct0s/disctopia-c2#34]
![Fatal error detected 08_03_2022 4_27_57 PM](https://user-images.githubusercontent.com/75936438/157225862-0604e018-4089-43a7-86ba-d812baa7036c.png)
To be honest, it worked perfectly the first time i executed it. After playing around with the commands for a while, the bot just went off, and then when i tried to run the backdoor again, it gave me this error

**Comment by 3ct0s** [comment]
The problem here is that your system gives limited permissions to your user and that is a rare case. In most cases, the file could have been with no problem. I could try to implement a check so that if the file cannot be created in that directory it would try something else.

**Comment by Hazed2004** [comment]
@harryk26005 are you sure you enabled intends in your discord developer portal -> applications -> yourapp -> bot....
You can find it there

**Comment by Hazed2004** [comment]
I've seen many people got this fatal error cuz they haven't enabled intends and it's fixed after enabling it, try this let us know how it goes
