### ISSUE TITLE
canot find py installer

### ISSUE THREAD

**Issue by Steamwarriors12** [3ct0s/disctopia-c2#36]
when fetched and build it gives an error  
 [+] > build

wine: cannot find '~.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe'
  
  
   tried  updating the system ,eddtiing the script while relinking it to a pyinstaller.py but it gives the same error please help.

**Comment by 3ct0s** [comment]
You did not follow the instructions from the Github repo. You forgot to run the setup to install the tool dependencies. Please follow the instructions and let me know how it goes.

**Comment by Steamwarriors12** [comment]
> You did not follow the instructions from the Github repo. You forgot to run the setup to install the tool dependencies. Please follow the instructions and let me know how it goes.

i did exactly the same as shown in your video.. also reinstalling python didnot fixed the issue .. it seems like there is no folder in my /home/kali/.wine/drive_c folder naming users .
 /users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe'

**Comment by 3ct0s** [comment]
Hi There,
The problem here is that you are running disctopia with the kali user and not with root. Please either run it with sudo or become the root user with sudo su. Then it should work.
