### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by AtacamaGT** [3ct0s/disctopia-c2#37]
The command is "executed" but nothing is send to token channel
![image](https://user-images.githubusercontent.com/89534308/157474405-98a5e4a2-ae7b-4e5c-b7d5-ea10ddf42c61.png)
![image](https://user-images.githubusercontent.com/89534308/157474536-77a4f757-fad4-4cc6-b2e5-224217a06854.png)

**Comment by kerropioz** [comment]
I have this issue too. It's a pain.

**Comment by falkensmz** [comment]
The problem most likely occurs because no token was found on the system. Make sure to check weather or not Discord is installed and also if you are/were logged in.

**Comment by 3ct0s** [comment]
> The problem most likely occurs because no token was found on the system. Make sure to check whether or not Discord is installed and also if you are/were logged in. Also, another reason may be that you might've not entered the right webhook when building the Disctopia RAT

@falkensmz is correct please make sure all of the above check ^
