### ISSUE TITLE
Fatal errors in 2nd and 3rd attempt.

### ISSUE THREAD

**Issue by HypervisingAfterburner** [3ct0s/disctopia-c2#39]
![unknown (3)](https://user-images.githubusercontent.com/101438162/157998363-6f90a9fc-9138-4da6-a713-b000bdfb0da5.png)
I've used the backdoor a total of three times, first on a computer of my own network, then on a friend's pc who asked me to give me the .exe to him and lastly on my school pc. The second and third attempts prompted up this error. (It's of note to mention that I uploaded one of the exes to my Mega account so my friend could download it and test it for himself). I'm not aware of what could be causing the backdoor to fail after being succesfully booted the other times around, any help?

**Comment by Hazed2004** [comment]
Are you using the same bot that you used before?

If not check have you enable intends in your discord developer portal

Let us know how it goes

**Comment by HypervisingAfterburner** [comment]
I used the same bot for all three, only changed the name of the exes
And I had both intends turned on

**Comment by HypervisingAfterburner** [comment]
The only other thing of note is that I did reset the token for the bot before rewritting the .json for the second time, could that have done anything to do with it too?

**Comment by Hazed2004** [comment]
Did you use the same generated token in settings.json?

**Comment by HypervisingAfterburner** [comment]
I did for those last two, with the third one being what's shown on the screenshot, is my best bet trying to delete everything and redoing it? Does me using a Discord Canary client also have to do anything with it

**Comment by Hazed2004** [comment]
> I did for those last two, with the third one being what's shown on the screenshot, is my best bet trying to delete everything and redoing it? Does me using a Discord Canary client also have to do anything with it

No no discord client is not even need to host this backdoor or something to do with it during build
Make sure you follow everything in the .MD files/video

**Comment by HypervisingAfterburner** [comment]
I did do that when I first built everything, is it posible I just messed up something while trying to do the other exes? Should I redo everything from scratch?

**Comment by HypervisingAfterburner** [comment]
Redid the bot after deleting the app, server and files on my pc and still got the same error
