### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by elliotlounds** [3ct0s/disctopia-c2#44]
[](https://user-images.githubusercontent.com/101060850/157917606-a641ac16-7c72-45eb-954c-274d277e16ba.png)

Hey 3ct0s, Ive done everything you have shown in the video multiple times But when i run these set up of command I never get the option to install python 3.8.9 to the root/win/....../python.exe It option doesn't even show up. So whenever I hit build it states that it cant locate the file. So i was wondering if you knew a solution to not having the option to install python.

cd disctopia-c2
sed $'s/\r$//' ./setup.sh > ./setup-new.sh
chmod +x setup-new.sh
sudo ./setup-new.sh

This is the error message im receiving
image

**Comment by elliotlounds** [comment]
![image](https://user-images.githubusercontent.com/101060850/158900411-503a5f5d-5c36-4aea-94a8-a02479fbed79.png)

**Comment by dennixone** [comment]
Hi,try it with X11 did you use wayland??What Linux Distribution did you use ?Am 17.03.2022 22:49 schrieb elliotlounds ***@***.***>:
