### ISSUE TITLE
Error with registry key or something (idk) 

### ISSUE THREAD

**Issue by MintOnTop** [3ct0s/disctopia-c2#47]
So I did all the steps in the installation guide (https://github.com/3ct0s/disctopia-c2/blob/main/inst/INSTALL.md) and entered them. But it was said that Python 3.8.9 already exists. I then had to choose between "Modify, Repair and Uninstall". Of course I clicked "repair". But then these messages came up: (entire console)
_┌──(root㉿kali)-[~]
└─# git clone https://github.com/3ct0s/disctopia-c2.git
fatal: destination path 'disctopia-c2' already exists and is not an empty directory.
                                                                             
┌──(root㉿kali)-[~]
└─# cd disctopia-c2                
                                                                             
┌──(root㉿kali)-[~/disctopia-c2]
└─# sed $'s/\r$//' ./setup.sh > ./setup-new.sh 
                                                                             
┌──(root㉿kali)-[~/disctopia-c2]
└─# chmod +x setup-new.sh
                                                                             
┌──(root㉿kali)-[~/disctopia-c2]
└─# sudo ./setup-new.sh
Hit:1 http://ftp.halifax.rwth-aachen.de/kali kali-rolling InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3.9 is already the newest version (3.9.11-1).
The following packages were automatically installed and are no longer required:
  libperl5.32 libx264-160 perl-modules-5.32
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 501 not upgraded.
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-pip is already the newest version (22.0.2+dfsg-1).
The following packages were automatically installed and are no longer required:
  libperl5.32 libx264-160 perl-modules-5.32
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 501 not upgraded.
Requirement already satisfied: prettytable in /usr/lib/python3/dist-packages (from -r requirements.txt (line 1)) (0.0.0)
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv          
Reading package lists... Done                                                
Building dependency tree... Done
Reading state information... Done
wine is already the newest version (5.0.3-3).
The following packages were automatically installed and are no longer required:
  libperl5.32 libx264-160 perl-modules-5.32
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 501 not upgraded.
python-3.8.9.exe already exists.
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
002f:err:mscoree:LoadLibraryShim error reading registry key for installroot
Collecting keyboard==0.13.5
  Using cached keyboard-0.13.5-py3-none-any.whl (58 kB)
Collecting pywin32==303
  Using cached pywin32-303-cp38-cp38-win32.whl (8.5 MB)
Collecting pycryptodome==3.12.0
  Using cached pycryptodome-3.12.0-cp35-abi3-win32.whl (1.8 MB)
Collecting pyautogui==0.9.53
  Using cached PyAutoGUI-0.9.53.tar.gz (59 kB)
Collecting pyinstaller==4.2
  Using cached pyinstaller-4.2.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\python.exe' 'C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\users\root\Temp\tmpw0krcflw'
         cwd: C:\users\root\Temp\pip-install-41ewvy7g\pyinstaller
    Complete output (42 lines):
    Traceback (most recent call last):
      File "C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 280, in <module>
        main()
      File "C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py", line 133, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\build_meta.py", line 188, in prepare_metadata_for_build_wheel
        self.run_setup()
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\build_meta.py", line 281, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\build_meta.py", line 174, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 75, in <module>
        setup(
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\__init__.py", line 79, in setup
        return distutils.core.setup(**attrs)
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 122, in setup
        dist.parse_config_files()
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\dist.py", line 832, in parse_config_files
        setupcfg.parse_configuration(
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 167, in parse_configuration
        meta.parse()
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 446, in parse
        section_parser_method(section_options)
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 417, in parse_section
        self[name] = value
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 238, in __setitem__
        value = parser(value)
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 552, in _parse_version
        return expand.version(self._parse_attr(value, self.package_dir, self.root_dir))
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\setupcfg.py", line 372, in _parse_attr
        return expand.read_attr(attr_desc, package_dir, root_dir)
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\expand.py", line 194, in read_attr
        module = _load_spec(spec, module_name)
      File "C:\users\root\Temp\pip-build-env-8ic6jzp2\overlay\Lib\site-packages\setuptools\config\expand.py", line 214, in _load_spec
        spec.loader.exec_module(module)  # type: ignore
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "C:\users\root\Temp\pip-install-41ewvy7g\pyinstaller\PyInstaller.py", line 16, in <module>
        from PyInstaller.__main__ import run
    ModuleNotFoundError: No module named 'PyInstaller.__main__'; 'PyInstaller' is not a package
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\python.exe' 'C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\users\root\Temp\tmpw0krcflw' Check the logs for full command output.
WARNING: You are using pip version 20.2.3; however, version 22.0.4 is available.
You should consider upgrading via the 'C:\users\root\Local Settings\Application Data\Programs\Python\Python38-32\python.exe -m pip install --upgrade pip' command.
                                                                             
┌──(root㉿kali)-[~/disctopia-c2]
└─#_

**Comment by blummy1** [comment]
im getting same error

**Comment by blummy1** [comment]
have u fixed it?

**Comment by UnknownLemonade** [comment]
Nah sorry I have not fixed it, but you can ask a few ppl in the dc, they know how to fix this Am 07.04.22, 18:23 schrieb blummy1 ***@***.***>:

   
  have u fixed it?
