### ISSUE TITLE
Error with pretty table

### ISSUE THREAD

**Issue by lolipopsk2** [3ct0s/disctopia-c2#52]
Error:

Traceback (most recent call last):
  File "C:\Users\xxx\OneDrive\Dokumenty\disctopia-c2-1.0.3\builder.py", line 7, in <module>
    from prettytable import PrettyTable
ModuleNotFoundError: No module named 'prettytable'

Please someone help, i installed the pretty table but it still dont work.

**Comment by hey000hey** [comment]
same for me

**Comment by dylan1013** [comment]
you just use the command

python install -r requirements.py

**Comment by hey000hey** [comment]
it says there's no such file

btw i also tried requirments.txt
