### ISSUE TITLE
Is there any way to delete the backdoor

### ISSUE THREAD

**Issue by oceanwaterxdd** [3ct0s/disctopia-c2#56]
So if i ran the backdoor on my main pc, how do i delete it

**Comment by philip223** [comment]
kill the task as it will always be running and then just delete it, if you want to do it through the bot just write a simple batch script to do all those steps, upload it with the bot and run it (!cmd) command.

**Comment by 3ct0s** [comment]
I updated the tool and now it has a self-destruct feature. You can use it with the command !selfdestruct AGENT-ID and this will permanently delete any trace of disctopia on the target computer.
If you just want to terminate the connection you can just execute the command !terminate AGENT-ID
