### ISSUE TITLE
Builder error

### ISSUE THREAD

**Issue by normaliok** [3ct0s/disctopia-c2#65]
![Снимок экрана 2022-06-23 135513](https://user-images.githubusercontent.com/35446022/175283350-7eebbb32-82f2-4a16-beaa-00354162ba74.jpg)

**Comment by normaliok** [comment]
FileNotFoundError: Cannot find a file

**Comment by 3ct0s** [comment]
Hi There,
Did you follow the installation process for windows or are you using your own python version? The tool needs its own python version.

**Comment by 3ct0s** [comment]
Are you using the **venv/Scripts/python.exe builder.py** command to start the builder?

**Comment by normaliok** [comment]
> Are you using the **venv/Scripts/python.exe builder.py** command to start the builder?

Of course

**Comment by dennixone** [comment]
If you use Python Environment and know the correct path it will Work
