### ISSUE TITLE
Config error

### ISSUE THREAD

**Issue by normaliok** [3ct0s/disctopia-c2#66]
I've pasted all options into settings.json, but config list is empty
![Снимок экрана 2022-06-23 135828](https://user-images.githubusercontent.com/35446022/175283946-196909ce-7bae-4a35-8c9a-529a89c9f4da.jpg)

**Comment by 3ct0s** [comment]
Hi There,
You need to run the **fetch** command to fetch the settings from the settings.json file

**Comment by normaliok** [comment]
There is no any information about fetch in your Build Guide

**Comment by 3ct0s** [comment]
This is it: 
![image](https://user-images.githubusercontent.com/74763463/175291293-14abdde3-9d80-49b0-934a-c729637d799f.png)

**Comment by 3ct0s** [comment]
Its in the build guide

**Comment by normaliok** [comment]
![Снимок экрана 2022-06-23 162721](https://user-images.githubusercontent.com/35446022/175310265-37a98b6d-1f07-4448-8900-f752c7c4f8b2.jpg)

**Comment by normaliok** [comment]
Dude, I think you should at least check your guides instead of argue

**Comment by 3ct0s** [comment]
I am not the one arguing here. You are obviously not following the commands from the guides from what I can see in the CMD title. You are running python.exe followed by the path to the builder.py script. Please head to the disctopia-c2 folder from your command prompt using the cd command and then run the **venv\Scripts\python.exe builder.py**  command. If you have done everything correctly and the PowerShell setup was done correctly it should work.

Also, there is nothing wrong with the guides. I just don't think you get their point. They are a step-by-step guide on how to install and use disctopia on machines. No need for excessive information

**Comment by 3ct0s** [comment]
This is happening because your terminal is sitting in another directory. The builder script is trying to find the settings.json file which does not exist in your current directory. Like I said to fix this you need to navigate to the disctopia-c2 directory.
