### ISSUE TITLE
Why Python for Windows under Linux?

### ISSUE THREAD

**Issue by normaliok** [3ct0s/disctopia-c2#67]
After starting **sudo ./setup-new.sh** from your setup guide, the python for windows downloading started. Why? And, of course, I had a lot of errors.
![Снимок экрана 2022-06-23 143806](https://user-images.githubusercontent.com/35446022/175290737-e36212c6-20d0-4df5-a21f-4cd66ff4b8c6.jpg)
![Снимок экрана 2022-06-23 143829](https://user-images.githubusercontent.com/35446022/175290743-39773bc6-e099-40c0-a26b-7e6949395a2c.jpg)

**Comment by 3ct0s** [comment]
Hi There,
On Linux, in order to create Windows EXEs with Python, you need to run it over wine which simulates a windows machine.

**Comment by normaliok** [comment]
Come on, dude! Where it's described in your guides? You wrote only about **setup-new.sh**
![Снимок экрана 2022-06-23 144744](https://user-images.githubusercontent.com/35446022/175291734-a18614cd-9833-4416-9fd0-2e2e7d808e46.jpg)

**Comment by 3ct0s** [comment]
Hi There,
Why do you need to know that? It is part of the needed dependencies which are required in order for it to work. I don't see what the problem is with installing wine and python for windows on it...

**Comment by 3ct0s** [comment]
The installation guide is supposed to include the needed commands and steps to install Disctopia. What you have to do is follow them. If you want to learn more about how the tool works or what it requires to work you can ask me here.

**Comment by normaliok** [comment]
> What you have to do is follow them

Ok, I'm following. I'm following step-by-step from your guide. And I get a lot of errors. What I am doing wrong?

**Comment by Pasch0** [comment]
normaliok, you opened 3 issues questioning with arrogance as if the guide was unclear and the project dysfunctional. As a fan of the project, I feel bad for the developer who has to explain himself to an arrogant person who doesn't know what he's doing. Study, understand, write your own code and don't make others waste time with your ignorance.

**Comment by 3ct0s** [comment]
@normaliok based on your issues. I can see that you are doing stuff on your own. The guide is an INSTALLATION AND USAGE GUIDE. There is no need for further explanation on the topics you brought up. These things belong to a more general wiki page rather than in the guide. 

As for the tool not working for you, this is a **(YOUR COMPUTER)** issue, plus the fact that you were doing stuff on your own without following the guide commands etc does not help. If you think the guide is shit then you can leave :)
