### ISSUE TITLE
so im in replit at the run build,py part and i just get No module named 'distro'

### ISSUE THREAD

**Issue by kingeggobandit** [3ct0s/disctopia-c2#68]
python3 builder.py
Traceback (most recent call last):
  File "builder.py", line 7, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'

**Comment by CuadritoFeliz** [comment]
Bro, seriusly.... you need to make that on pc

**Comment by CuadritoFeliz** [comment]
And follow the tutorial

**Comment by 3ct0s** [comment]
Hi There,
Can you please try to run the command **pip install distro**

**Comment by CuadritoFeliz** [comment]
install requirements.txt

**Comment by kingeggobandit** [comment]
I got you I just wasn't sure if I was supposed to run this in Cali or if I'm supposed to run this on repelit to run the bot 24/7 with uptime servers.

I did follow the directions and everything else installed perfectly I was just running into no distro issues and I just didn't know what was going on.

There's been no issues so I was assuming it was a new build still getting its testing

**Comment by kingeggobandit** [comment]
got it working after manualy running  pip install distro

**Comment by 3ct0s** [comment]
Essentially the code for the Bot is in the EXE. The target machine is executing the code for the BOT on their computer.

**Comment by Hazed2004** [comment]
replit doesnt allow you to install wine, so it will not work in replit ig

**Comment by 3ct0s** [comment]
Inactive issue, closing
