### ISSUE TITLE
handler issues

### ISSUE THREAD

**Issue by rogldicksn** [3ct0s/disctopia-c2#70]
1: i get this when i run the build .exe
![image](https://user-images.githubusercontent.com/76434629/178131427-42e72f3b-0077-4422-903d-a179369cff5f.png)

2: The build.exe file is about 64MB.. can this be reduced to about 1 or 2MB ?

**Comment by rogldicksn** [comment]
![image](https://user-images.githubusercontent.com/76434629/178131409-7674996b-aef4-4350-a928-c67ae6e774cf.png)

**Comment by d4rks0ul555** [comment]
ModuleNotFoundError: No module named 'discord'

please help
