### ISSUE TITLE
build issue

### ISSUE THREAD

**Issue by BIRTAX38** [3ct0s/disctopia-c2#73]
wine: failed to open "/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe": c0000135

[+] The Backdoor can be found inside the "dist" directory

DO NOT UPLOAD THE BACKDOOR TO VIRUS TOTAL

builder dosen't work

**Comment by cat-policlot** [comment]
try builder in windows 10

**Comment by PureBlood6** [comment]
> try builder in windows 10

It's says:

Traceback (most recent call last):
  File "C:\Users\"User"\Desktop\Builder\builder.py", line 7, in <module>
    import distro
ModuleNotFoundError: No module named 'distro'

I don't know what to do I'm facing the same issue.

**Comment by GizziXZ** [comment]
> > try builder in windows 10
> 
> It's says:
> 
> Traceback (most recent call last): File "C:\Users"User"\Desktop\Builder\builder.py", line 7, in import distro ModuleNotFoundError: No module named 'distro'
> 
> I don't know what to do I'm facing the same issue.

pip install -r requirements.txt

**Comment by Anonymous0101010010** [comment]
same bruh
