### ISSUE TITLE
wine: giving failed to open error with python.exe

### ISSUE THREAD

**Issue by Kaleem137** [3ct0s/disctopia-c2#83]
getting this error when running ./setup-new.sh
wine: failed to open "/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/python.exe": c0000135 Done
![2022-11-17 00_19_59-Window](https://user-images.githubusercontent.com/87889855/202274082-22058f13-9b44-4a3a-a08a-586e71a5a925.png)

**Comment by nicksilverlight** [comment]
Same

**Comment by spicy-bear** [comment]
![image](https://user-images.githubusercontent.com/26792640/205460795-d81bc974-f84e-43e3-838e-d3d6ee10cc06.png)
bump
