### ISSUE TITLE
interact with multiple agents at at once

### ISSUE THREAD

**Issue by Programmer1603** [3ct0s/disctopia-c2#87]
I recently came across this github repo and really liked it, however i noticed that there is no command to interact with all agents at once.
If i missed it please let me know. Could you please add an option for every command like [all] to adress all agents at once?
Thank you and have wonderful holidays!

**Comment by cryptolab-deep** [comment]
That would be very useful, I agree with your idea. In any case, I cannot enter commands with an agentID. I don't understand how they should be formulated. What exactly should I enter instead of {AGENT-ID}? Would you give me an example with a random ID? Thanks

**Comment by Programmer1603** [comment]
I am bot quite sure myself, however if you create a server using the template provided there should be a text channel called "agent-online". Maybe there is an index of all the IDs? (Again i dont know it myself this is just a guess)

**Comment by cryptolab-deep** [comment]
I find ID, but I do not know how to formulate the command, as every attempt has failed.

**Comment by cryptolab-deep** [comment]
It was not very calling but I understood how to set the command. In any case, an implementation of a multi-target action in the same command would be interesting.

**Comment by 3ct0s** [comment]
Hey there, Merry Christmas! Sorry, I only saw this just now. Thank you for showing interest in my repository. For the agent id question, you are supposed to use the bot commands like **!cmd 4098 calc.exe**. In this case, 4098 is the ID of the agent. You can get that ID when he gets online and a message is sent to the agent's online channel.

As for the multi-target action, there is such a feature but only on the **cmd** command. If you run the !cmd command without specifying a target agent, the command will be executed on all online agents. I figured this is the best and only command that would hold this feature, hence the name Disctopia **C2** (Command and control)

**Comment by 3ct0s** [comment]
There is a small issue with the cmd command that I need to fix. Essentially when you do indeed run a command on all target agents and the command gives an error or causes Disctopia to bug, it crashes the whole botnet which essentially makes your agents useless if you haven't enabled persistence. This is a top priority.

**Comment by Programmer1603** [comment]
Ok thank you for the explanation and quick response!
