### ISSUE TITLE
What to enter in "auto-persistent"

### ISSUE THREAD

**Issue by YaGoatt** [3ct0s/disctopia-c2#90]
Hi, first of all, thanks for the easy guide. It makes everything pretty easy. but I guess you added this part of "auto-persistent" after the last update and I don't know what to enter here. The first time I tried it, I typed true because it looks like "auto-keylogger". But when I build and run it:
Traceback (most recent call last):
   File "Builder.py", line 36, in <module>
NameError: name 'true' is not defined
As far as I understand, I will enter something other than true, if you can help I will be happy, thanks in advance.

**Comment by philip223** [comment]
line 36 of the main.py in the code folder  is `PERSISTENT = {PERSISTENT}` which relates to `newfile = newfile.replace("{PERSISTENT}", str(self.PERSISTENT))` a really easy fix could just be editing line 36 on main.py and replacing it with `PERSISTENT = True` and that should fix it.
