### ISSUE TITLE
Where i can find the Agent-ID for execute commands

### ISSUE THREAD

**Issue by Victor200319** [3ct0s/disctopia-c2#93]
I been trying to find the Agent-ID for hours for make commands like ->!screenshot {AGENT-ID} but i cant make it work 

![image](https://user-images.githubusercontent.com/115377744/223522238-7f4077e1-5b09-4c9e-a4c9-b697bd62cc68.png)
 thats an example of my other pc

**Comment by Gumbobrot** [comment]
#2456 is the agent id

**Comment by Gumbobrot** [comment]
@Victor200319
