### ISSUE TITLE
How to go to directory with spaces?

### ISSUE THREAD

**Issue by SourCandy80** [3ct0s/disctopia-c2#94]
I keep getting this error:

![image](https://user-images.githubusercontent.com/111071796/223589046-2cdc3ffd-608d-4b0c-81f9-e06a6cf2ccce.png)

This is just an example, I already know of the credentials function but I still need to access other folders with spaces.

**Comment by Gumbobrot** [comment]
wrong path and you obv need to even decode/decrypt the file if you got it

**Comment by 3ct0s** [comment]
Have you tried adding quotes on the path? I don't remember if that works or not

**Comment by Gumbobrot** [comment]
yeah try it with quotes and \\
@SourCandy80

**Comment by SourCandy80** [comment]
I tried quotes, escaping using \and ^

I have confirmed the path exists @Gumbobrot and yes obviously I would have to decrypt it. Please do not act like it is so clear. The way the program works is by separating the commands by using spaces as the separator values, thus resulting in not being able to put paths with spaces in them.

**Comment by Gumbobrot** [comment]
then code your own shit buddy or fix the code

**Comment by SourCandy80** [comment]
> then code your own shit buddy or fix the code

I already have. Making an improved version for my use case already. This project seems a bit dead so I just added a few features I wanted and fixed the numerous issues.

**Comment by Gumbobrot** [comment]
ohhh good
