### ISSUE TITLE
Build Issue With Wine's Python

### ISSUE THREAD

**Issue by Senturon** [3ct0s/disctopia-c2#96]
Hello so I have followed the installation steps and i got to this point where i need to build the program.. I run the steps that it had asked me to do and this is what i got. Please keep in mind I am using Kali Linux amd64x on a virtualbox. Please let me know if there is anything We can do to solve this issue.

`[+] > build

Are you sure everything is setup correctly? Y/N 
y

[+] Building the Backdoor
[+] Please wait...

3148 INFO: PyInstaller: 5.3
3149 INFO: Python: 3.8.9
3153 INFO: Platform: Windows-10-10.0.18362
3167 INFO: wrote Z:\home\kali\disctopia-c2\C2 bot.spec
3212 INFO: UPX is not available.
3274 INFO: Extending PYTHONPATH with paths
['Z:\\home\\kali\\disctopia-c2']
wine: Unhandled illegal instruction at address 083169C9 (thread 0110), starting debugger...`

After that the python program gave me a popout stating in the screenshot below: 

![image](https://user-images.githubusercontent.com/74071421/225480586-553581d6-eab4-4ae2-ad59-a1ced123aa85.png)

**Comment by Gumbobrot** [comment]
do it on windows

**Comment by 3ct0s** [comment]
This is also a new one. Did wine install with no errors? Was the disctopia installation done properly?

**Comment by Gumbobrot** [comment]
> This is also a new one. Did wine install with no errors? Was the disctopia installation done properly?

yeah bro it's because disctopia is shit

**Comment by 3ct0s** [comment]
Disctopia has not been properly updated in a long time :)

**Comment by Gumbobrot** [comment]
> Disctopia has not been properly updated in a long time :)

I tried it months ago, wasn't even working at that time, there is so much to clean and fix

**Comment by 3ct0s** [comment]
The last actual update was in July. I've been experimenting with new features but I don't have the time I had back then to keep the project updated every so often.

**Comment by Gumbobrot** [comment]
> The last actual update was in July. I've been experimenting with new features but I don't have the time I had back then to keep the project updated every so often.

then search for contributors bro
