### ISSUE TITLE
0144:err:mscoree:LoadLibraryShim error reading registry key for installroot

### ISSUE THREAD

**Issue by atanu2679** [3ct0s/disctopia-c2#99]
![Capture](https://user-images.githubusercontent.com/75174754/231825330-7190a0a4-5e55-4139-b980-034f111951a8.PNG)
how can i fix this 
im using kali..
i have all those folder still its showing me error

**Comment by 3ct0s** [comment]
Did you run the setup succesfully?

**Comment by atanu2679** [comment]
Now its working fine....

I did manually ....
